name: Daily AI Update
on:
  schedule:
    - cron: '0 22 * * *' # 한국 시간 오전 7시
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    # 아래 env 부분을 추가하면 경고 메시지가 사라집니다.
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 
      
      - name: Python Setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install Libraries
        run: pip install requests beautifulsoup4
        
      - name: Run Script
        run: python update_news.py
        
      - name: Update GitHub Data
        run: |
          git config --global user.name 'GitHub Action Bot'
          git config --global user.email 'action@github.com'
          git add data.json
          git commit -m "Auto Update: Latest AI News" || echo "No changes"
          git push
